name: Go - Test & Lint
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go build
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: go mod download
    - run: go build ./cmd/controller
  test:
    runs-on: ubuntu-latest
    name: Go test
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: go mod download
    - run: go test -v ./...
  lint:
    runs-on: ubuntu-latest
    name: Go lint
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download GolangCI-Lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
    - name: Run golangci-lint run
      run: $(go env GOPATH)/bin/golangci-lint run --verbose --timeout 5m
      